DROP TABLE IF EXISTS OrderItems;

DROP TABLE IF EXISTS Orders;

DROP TABLE IF EXISTS Products;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS UnitsOfMeasure;

DROP TABLE IF EXISTS Suppliers;

DROP TABLE IF EXISTS Manufacturers;

DROP TABLE IF EXISTS ProductCategories;

DROP TABLE IF EXISTS OrderStatuses;

DROP TABLE IF EXISTS UserRoles;